### ISSUE TITLE
Feature 1: User can view the catalog of available snowboards

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to scroll through and view the different snowboard products offered. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is on the home page, they can either click on 'Shop the Collection' or 'Products' links which will take them to a view of all of the different snowboards offered. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop:
<img width="832" alt="Screen Shot 2022-11-07 at 11 42 28 AM" src="https://user-images.githubusercontent.com/60860374/200400028-772ae784-da87-4f2f-994d-b2d5ce46cafc.png">

Mobile: 
<img width="262" alt="Screen Shot 2022-11-07 at 11 40 49 AM" src="https://user-images.githubusercontent.com/60860374/200399723-d41ea3a0-eb2d-4d88-995d-1be4f7509c27.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create database through command line with createdb traderSnows
- [x] Paste the schema from DB Designer into `schema.sql`
  - [x] Replace all instances of "public.someTable" with "public"."someTable"
- [x] Add all products to the database by writing SQL insert statements in `data.sql`
  - [x] Insert values for name, price, imageUrl, description, profileType, flex, shape, edgeTech, abilityLevel, terrain into the snowboards table 
  - [x] Insert values for size into the sizes table
  - [x] Insert values for edgeTechName and edgeTechDescription into the edgeTech table
  - [x] Insert values for profileName and profileDescription into the profileTypes table
  - [x] Insert values for shapeName and shapeDescription into the shapes table
- [x] Import the schema into the database ---> psql -d traderSnows -f schema.sql
- [x] Import the data into the database ---> psql -d traderSnows -f data.sql
- [x]  start pgweb to confirm the db was created and visit http://localhost:8081 to review the db

### ☁️ Server Tasks

- [x] Install all dependencies and dev-dependencies
- [x] Create an express server by requiring the express package, calling express and then using the listen method.
- [x] Define client-error function inside of `client-error.js`
- [x] Define errorMiddleware function inside of `error-middleware.js`
- [x] Require pg and create a database connection with new pg.Pool
- [x] Create a route for a 'GET' request to fetch the data from the database
  - [x] The imageUrl, productName, and price for each snowboard needs to be grabbed from the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create app component
- [x] Create a component to display navbar
  - [x] Create 'Products' anchor tag
  - [x] Use bootstrap utility classes and css to have the navbar reflect the wireframes
- [x] Create a component to display the products catalog
  - [x] Include a header that reads 'Women's Snowboards' 
  - [x] Send a fetch request for all snowboards and parse the response
    - [x] Map through each item to create a display for each product
    - [x] Each product should display the image, the name of the product, and the price
  - [x] Use bootstrap utility classes and css to have the catalog reflect the wireframes
    - [x]  Mobile view should display 2 products per row
    - [x] Desktop view should display 4 products per row 
- [x] Create a component to display the home page
  - [x] Create 'Shop the Collection' anchor tag
  - [x]  Use bootstrap utility classes and css to have the home page reflect the wireframes

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
