### ISSUE TITLE
Feature 2 : User can view detailed information on a particular snowboard

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view detailed information on a particular snowboard.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user clicks on a product of interest, the user will be brought to a page with more detailed information regarding the product. On mobile, they will be able to view/hide specs if they click on the arrow. On desktop, the specs will automatically be shown. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

desktop:
<img width="403" alt="Screen Shot 2022-11-07 at 11 45 07 AM" src="https://user-images.githubusercontent.com/60860374/200400571-c814d304-b141-468a-a9d1-6f148886a8b1.png">

mobile:
<img width="397" alt="Screen Shot 2022-11-07 at 11 47 02 AM" src="https://user-images.githubusercontent.com/60860374/200400897-520a960e-016d-42e5-a28b-f40ba8505464.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `index.js` to include another 'GET' request to fetch data for a specific productID from the database
  - [x] Use a select statement and join clauses to retrieve the name, available sizes, price, description, imageUrl, profileType, flex, shape, edgeTech, abilityLevel, and terrain
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update products component to render each product as an anchor tag
  - [x] Clicking on the anchor tag should take the user to the details of that product 
 - [x] Update app component to listen for hash changes and update state
   - [x] If path is 'products', display products page
   - [x] if path includes a product id, display the details of that products page
   - [x] if path is empty string, display home page
- [x] Create a component to display an individual product's details
  - [x] Both views will display the image, name, sizes, price and product details 
  - [x] Loop through fetch results to grab and display the sizes for each product
  - [x] Mobile view: Product specs are hidden and the user can view the specs by clicking on the accordion
    - [x] Use bootstrap accordion component to create the specs view
    - [x] Use bootstrap utility classes and css to have the catalog reflect the wireframes
  - [x] Desktop view: Product specs are shown automatically on load
    - [x] Use bootstrap utility classes and css to have the catalog reflect the wireframes 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
