### ISSUE TITLE
Feature 3: User can add a product to the shopping cart

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to add a product to their shopping cart

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the 'Add to cart' button, they are able to add the product to their shopping cart. They can also increase/decrease the quantity of the item. Once they add something to the cart, a modal appears that informs them that an addition to the cart was made. It includes a photo of the product and the product information (name, qty, size, price). They will be able to either 'x' out the modal on the top right or click on the 'Continue Shopping' button which will take the back to the catalog of products. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

desktop:
<img width="831" alt="Screen Shot 2022-11-07 at 11 54 23 AM" src="https://user-images.githubusercontent.com/60860374/200402201-48044fc3-a8dc-443e-a494-11adc1103eb5.png">

mobile:
<img width="393" alt="Screen Shot 2022-11-07 at 11 50 41 AM" src="https://user-images.githubusercontent.com/60860374/200401515-a7076e29-376c-4fa3-adad-ecf2e13e570f.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a 'POST' request to add items to a user's cart into the database
  - [x] Check for token
    - [x] If token is not present, create a token
      - [x] Use sql insert statement that will generate cartId
    - [x] if token is present, get the cartId associated with the token
  - [x]  Use sql insert statement that will add productId, quantity, and size based on token/cartId
  - [x]  Include token in the POST response
  - [x] Account for any potential errors 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update app component to store token in local storage
- [x] Add cart icon to navbar
- [x] Update product-details component to include:
  - [x] Change product-details to a form element to listen for submit events
  - [x] Sizes should become buttons that update state to help differentiate which product is added
  - [x]  'Add to Cart' button which will send a fetch request (post method) to the database
    - [x] Fetch request needs to send the productId and quantity, and size 
    - [x] Include token in fetch request
    - [x] User **needs** to select a size before adding to cart
- [x] Create a component to display modal anytime user adds an item to the cart
  - [x] Modal should include product name, product size, quantity, and price
  - [x] A "Continue Shopping' button that takes user back to list of products
  - [x] Use bootstrap utility classes and css to have the catalog reflect the wireframes

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
