### ISSUE TITLE
Feature 4: User can view their shopping cart

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view their shopping cart. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After users add a product to their cart, they will have three options. They can exit out the modal by clicking on the X. The second option is to click on the 'Continue Shopping' button which will take them to the catalog of products. The last option will be the view their cart with the 'Checkout Now' button. When the user clicks on that button, they will be taken to their shopping cart. The shopping cart will show all the items (and information on those items) they have in their cart as well as an order summary that includes the order total.

Users will also be able to view their shopping cart at any point by clicking on the shopping cart icon on the far right of the nav bar. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop:
<img width="832" alt="Screen Shot 2022-11-07 at 11 59 56 AM" src="https://user-images.githubusercontent.com/60860374/200403261-049b9635-88c1-4994-aaea-662b7c6d6ca6.png">

Mobile:
<img width="390" alt="Screen Shot 2022-11-07 at 12 00 25 PM" src="https://user-images.githubusercontent.com/60860374/200403343-273992a8-d7be-4ad5-83c1-4be642e79840.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a 'GET' route to fetch data from a user's cart
   - [x] Verify token and pull out cartId from the payload
  - [x] Use a select statement with join clauses to retrieve all the cart items and the name/price/qty/size of each item associated with the cartId
  - [x] Account for any potential errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update modal component to display "Checkout Now" anchor tag
  - [x] Update hash routing in the app component to display the cart view when 'Checkout Now' is clicked on 
- [x] Update shopping cart icon in the nav bar to an anchor tag that also leads to cart view when clicked on 
- [x] Create a component to display shopping cart
  - [x] Create a fetch request that includes the token to grab all the items in the shopping cart
    - [x]  Each item in the shopping cart should have the name, size, qty, and price
  - [x] Use bootstrap utility classes and css to have the shopping cart reflect the wireframes
- [x] Create a order summary component 
  - [x] The summary should display the subtotal, standard shipping, estimated taxes, and order total
  - [x]  Use bootstrap utility classes and css to have the shopping cart reflect the wireframes
- [x] Mobile: shopping cart items are on top of order summary
- [x] Desktop: shopping cart items are to the left of the order summary
- [x] If user has no products in the cart, show a message that reads your shopping cart is empty
  - [x] Include an anchor tag 'shop for gear' that takes the user to the list of products

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
