### ISSUE TITLE
Feature 5: User can remove an item from their shopping cart

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to remove items from their shopping cart

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user wants to remove an item from their shopping cart, they can click on the 'Remove Item' link that is underneath the price of each item in their shopping cart. Once they click on it, the item will be removed from their cart. If there are no products in the cart, the user will be shown a screen that indicates that the cart is empty. There will also be a 'Shop for gear' button underneath that will take the user to the catalog of products when clicked. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop:
<img width="832" alt="Screen Shot 2022-11-07 at 12 08 31 PM" src="https://user-images.githubusercontent.com/60860374/200404842-d6197cf3-33ec-42c2-bbc6-48dc5c7c6e49.png">

Mobile:
<img width="391" alt="Screen Shot 2022-11-07 at 12 07 57 PM" src="https://user-images.githubusercontent.com/60860374/200404722-89d3ba42-23b2-48c7-8e36-9ff1a4fa2528.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a delete route that grabs the cart id from the token and product number 
  - [x] Sql statement with that updates database where productId = productId AND cartId = cartId pulled from token
  - [x] Account for any potential errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `cart.jsx` to render a 'Remove Item' button on each item in the shopping cart
  - [x] Anytime a user clicks the button, it should send a delete request to the server 
  - [x] Use bootstrap utility classes and css to have it reflect the wireframes

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
