### ISSUE TITLE
Feature 6: User can increase/decrease the quantity of an item from the shopping cart

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to update the quantity of any item in their shopping cart. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user wants to update the quantity of a specific product in their shopping cart, they can do so by clicking the + or - buttons which are displayed above the price for each product. The quantity will not be able to go lower than 1. If a user wants to remove a product, they will have to click on 'Remove Item' instead. 

As the user updates the quantity of a product, the order summary/total will update accordingly.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop:
<img width="405" alt="Screen Shot 2022-11-07 at 12 17 50 PM" src="https://user-images.githubusercontent.com/60860374/200406608-beed59f8-4fd0-4da9-8500-973ab73da930.png">

Mobile:
<img width="189" alt="Screen Shot 2022-11-07 at 12 18 25 PM" src="https://user-images.githubusercontent.com/60860374/200406711-66939fa6-8b19-42c1-9125-0426424943f2.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a PATCH route that increases the quantity of product by 1
  - [x] Sql statement that updates database for quantity by 1 where productId = productId & cart Id = cartId
  - [x] Confirm that updating quantity also updates the total cost of the cart 
  - [x] Account for any potential errors
- [x] Update `server/index.js` to include a PATCH route that decreases the quantity of product by 1
  - [x] Sql statement that updates database for quantity by 1 where productId = productId & cart Id = cartId
  - [x] Confirm that updating quantity also updates the total cost of the cart 
  - [x] Account for any potential errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update cart component
  - [x] Each list item should have  + and - icons surrounding the quantity
  - [x] Click event listeners on each icon to send fetch request
  - [x] + fetch request should increase shown quantity by 1
  - [x]  - fetch request should decrease shown quantity by 1
  - [x] Confirm that updating quantity also updates the total cost of the cart in order summary

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
