### ISSUE TITLE
Feature 7: User can make a purchase 

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to make a purchase. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user would like to make a purchase, they can click on the 'Proceed to Payment' button. That takes them to a screen that requires them to fill out personal information (email, first/last name, address). Once the information is provided, the user clicks on the 'Continue to Payment' button. That takes them to a screen that requires them to fill out payment information. Once the payment information is verified, the user clicks on 'Place Order'. When the order is successful, the user is taken back to the home page and is shown a modal with a thank you message. The user can click 'Continue Shopping' to view the catalog of products or close out the modal by clicking on the 'x'.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop:
<img width="828" alt="Screen Shot 2022-11-07 at 1 37 37 PM" src="https://user-images.githubusercontent.com/60860374/200420723-d54e7242-adeb-4735-b926-8bed441902d9.png">
<img width="838" alt="Screen Shot 2022-11-07 at 1 37 55 PM" src="https://user-images.githubusercontent.com/60860374/200420777-53e8e1d5-c497-423a-9b6b-34436e733d5c.png">

Mobile:
<img width="814" alt="Screen Shot 2022-11-07 at 1 37 10 PM" src="https://user-images.githubusercontent.com/60860374/200420663-7ea6e8c2-3fb5-4f0c-84a9-32bd58ae8e01.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive a 'POST' request to add personal information from the user
  - [x] Sql statement will add email, first name, last name, and address info into database 
- [x]  Update `server/index.js` to receive a 'POST' request to add order information after user has purchased items
  - [x] Sql statement will add cart id, customerId, total, and timestamp to the database 
  - [x] Update the value of the purchased column of the cartId to true
- [x] Account for any potential errors 
- [x] Install stripe library and create paymentIntent
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Calculate order total and use that amount to charge customer (not front-end)

### ⚡ Client Tasks

- [x] Update cart component to include a 'Proceed to checkout' anchor that takes user to step 1 (entering personal info) of the checkout process
  - [x] Update hash routing to 'personal-info'  to display the checkout page component
- [x] Create checkout page/component  
  - [x] Create personal info component
    - [x] Includes a form that gathers email, first name, last name, and address 
    - [x] Includes a 'continue to payment' anchor tag that takes the user to step 2 of the checkout process
    - [x] Update hash routing in app component to display the payment information component 
    - [x] Includes order summary component
    - [x]  Use bootstrap utility classes and css to have the modal reflect the wireframes
  - [x] Create checkout component with stripe elements
    - [x] Fetch payment intent
    - [x] Includes order summary component
    - [x]  Includes 'place order' anchor tag that takes user to the products page
    - [x] Create a fetch request (post method) that sends the form inputs, cart id, customer id, total, timestamp to the server 
    - [x] Use bootstrap utility classes and css to have the modal reflect the wireframes
- [x] Move order summary out of the cart file and make it a separate component
  - [x] Define method to estimate taxes 
  - [x] Have order summary show same numbers across multiple pages
- [x] Create a order confirmation component
  - [x] Modal that shows a thank you message
  - [x] Modal includes a 'Continue Shopping' anchor tag that directs users to the products page 
  - [x] Use bootstrap utility classes and css to have the modal reflect the wireframes

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
